# Change these first
owner: mpraglowski # Your GitHub username
repo: status.praglowski.com # Your GitHub repository name

# Add your sites here
sites:
  - name: praglowski.com
    url: https://praglowski.com
  - name: praglowska.com
    url: https://praglowska.com
  - name: tomek.praglowski.com
    url: https://tomek.praglowski.com
  - name: slub.praglowski.com
    url: https://slub.praglowski.com
  - name: talks.praglowski.com
    url: https://talks.praglowski.com
  - name: europebycar.info
    url: https://europebycar.info

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.praglowski.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sites Status
  introTitle: "Sites status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
